name: Configure Terraform
description: Setup Terraform

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-session-token:
    description: 'AWS Session Token'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token}}
        aws-region: ${{ inputs.aws-region}}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Init Terraform
      shell: bash
      run: terraform init