name: Configure Terraform
description: Setup Terraform

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-session-token:
    description: 'AWS Session Token'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ input.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ input.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ input.AWS_SESSION_TOKEN}}
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Init Terraform
      shell: bash
      run: terraform init