name: Configure Terraform
description: Setup Terraform

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_session_token:
    description: 'AWS Session Token'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-session-token: ${{ inputs.aws_session_token}}
        aws-region: ${{ inputs.aws_region}}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Init Terraform
      shell: bash
      run: terraform init