name: Configure Terraform
description: Setup Terraform

runs:
  using: composite
  steps:
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
        aws-region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Init Terraform
      run: terraform init