name: Deploy
description: |
  This workflow uses Terraform to deploy the AWS infrastructure.
  It applies the Terraform configuration to create the infrastructure.

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Terraform
      uses: ./.github/workflows/actions/configure-terraform
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Save the "terraform.tfstate" file
      uses: actions/upload-artifact@v4
      with:
        name: terraform.tfstate
        path: terraform.tfstate
        retention-days: 1
