name: Use Terraform to Deploy AWS Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Terraform
      uses: ./.github/workflows/actions/configure-terraform
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Create a Destroy Plan
      run: terraform plan -destroy -out=destroy.plan

    - name: Save the Destroy Plan
      uses: actions/upload-artifact@v3
      with:
        name: destroy.plan
        path: destroy.plan
