name: Deploy Terraform to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Terraform
      uses: ./.github/workflows/actions/configure-terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve