name: Use Terraform to Destroy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      artifact-run-id:
        description: The run ID of the artifact to download
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      actions: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Terraform
      uses: ./.github/workflows/actions/configure-terraform
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Download the Destroy Plan
      uses: actions/download-artifact@v4
      with:
        name: destroy_plan
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: ${{ github.event.inputs.artifact-run-id }}

    - name: Apply Terraform
      run: terraform apply destroy_plan