name: Destroy
description: |
  This workflow uses Terraform to destroy the AWS infrastructure.
  It downloads the destroy plan artifact and applies it to destroy the infrastructure.

on:
  workflow_dispatch:
    inputs:
      artifact-run-id:
        description: The run ID of the Action that generated the "terraform.tfstate" artifact.
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      actions: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Terraform
      uses: ./.github/actions/configure-terraform
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Download the "terraform.tfstate" file
      uses: actions/download-artifact@v4
      with:
        name: terraform.tfstate
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: ${{ github.event.inputs.artifact-run-id }}

    - name: Destroy Terraform
      run: terraform destroy -auto-approve